version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "8888:80"
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge



#  postgres:
#    container_name: db
#    image: postgres:alpine
#    environment:
#      POSTGRES_USER: db_user
#      POSTGRES_PASSWORD: db_password
#      POSTGRES_DB: db_name
#    ports:
#      - "15432:5432"